### ISSUE TITLE
error in code

### ISSUE THREAD

**Issue by Sanghamitra1234** [syedhope/SIFT#1]
the code is showing some errors have you tested it

**Comment by syedhope** [comment]
Yes, I have. Can you please share the errors?

**Comment by Sanghamitra1234** [comment]
In many places i got index error and in find_key the parameters u were
passing didnt have the same length
. I am stuck in descriptor part,  if u can help that will be highly
respected.  Please

**Comment by Sanghamitra1234** [comment]
Let's say 6 Neighbors  he 1 2 2 4 3 1 and you ignored the cases where
m(I,j) is 4 and m(I,j) is 1
So i fixed those error and in theta i was getting nan.  I fixed them too.

**Comment by syedhope** [comment]
Did you try using the sample input images included in this repository? 

I tried to reproduce the error but couldn't. [It works fine for me](https://drive.google.com/open?id=0B2o4ZpVQh__LeFl0bHF3eDhZVFk).

**Comment by Sanghamitra1234** [comment]
Yep i did the same but it wasnot working.  So i changed the image.  Got a
simpler image of digit 4

**Comment by syedhope** [comment]
could you please try the code for the images given in the repository and share the errors?

**Comment by syedhope** [comment]
Could you please share the screenshot of the errors you got?

**Comment by LiutsingWo** [comment]
hi@syedhope ,in line 137 -'for j,k in area[ z]:' , 'z' isnt define , is it right ?
